application: gagglepitttest
runtime: python27
api_version: 1
version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico
- url: /static
  static_dir: static
- url: /css
  static_dir: css
- url: /font
  static_dir: font
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /.*
  script: code.app

